{"name": "失败测试", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_login.TestLogin object at 0x7f9436f462c0>\n\n    @allure.story(\"测试失败效果\")\n    @allure.title(\"失败测试\")\n    def test_three(self):\n>       assert False\nE       assert False\n\ntestcase/test_login.py:105: AssertionError"}, "start": 1652845175324, "stop": 1652845175324, "uuid": "e780f114-f502-436e-9b1a-787803931765", "historyId": "6ea53df24699696bbe80325eb04d19e4", "testCaseId": "9ea88b76978b417df0aaa6168c67eeda", "fullName": "testcase.test_login.TestLogin#test_three", "labels": [{"name": "feature", "value": "登录以及增删改查测试项目"}, {"name": "story", "value": "测试失败效果"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "tangzhongkaideMacBook-Pro.local"}, {"name": "thread", "value": "56048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}